/*
Salesforce Platform REST API

Testing DefaultApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package rest

import (
	"context"
	openapiclient "github.com/russman12/go-force/pkg/rest"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_rest_DefaultApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefaultApiService SObjectDescribe", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var sObject string

		resp, httpRes, err := apiClient.DefaultApi.SObjectDescribe(context.Background(), sObject).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
