/*
Salesforce Platform REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 56.0
Contact: russell-laboe@outlook.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// SObjectDescribes struct for SObjectDescribes
type SObjectDescribes struct {
	Encoding     *string           `json:"encoding,omitempty"`
	MaxBatchSize *int32            `json:"maxBatchSize,omitempty"`
	Sobjects     []SObjectDescribe `json:"sobjects,omitempty"`
}

// NewSObjectDescribes instantiates a new SObjectDescribes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSObjectDescribes() *SObjectDescribes {
	this := SObjectDescribes{}
	return &this
}

// NewSObjectDescribesWithDefaults instantiates a new SObjectDescribes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSObjectDescribesWithDefaults() *SObjectDescribes {
	this := SObjectDescribes{}
	return &this
}

// GetEncoding returns the Encoding field value if set, zero value otherwise.
func (o *SObjectDescribes) GetEncoding() string {
	if o == nil || isNil(o.Encoding) {
		var ret string
		return ret
	}
	return *o.Encoding
}

// GetEncodingOk returns a tuple with the Encoding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SObjectDescribes) GetEncodingOk() (*string, bool) {
	if o == nil || isNil(o.Encoding) {
		return nil, false
	}
	return o.Encoding, true
}

// HasEncoding returns a boolean if a field has been set.
func (o *SObjectDescribes) HasEncoding() bool {
	if o != nil && !isNil(o.Encoding) {
		return true
	}

	return false
}

// SetEncoding gets a reference to the given string and assigns it to the Encoding field.
func (o *SObjectDescribes) SetEncoding(v string) {
	o.Encoding = &v
}

// GetMaxBatchSize returns the MaxBatchSize field value if set, zero value otherwise.
func (o *SObjectDescribes) GetMaxBatchSize() int32 {
	if o == nil || isNil(o.MaxBatchSize) {
		var ret int32
		return ret
	}
	return *o.MaxBatchSize
}

// GetMaxBatchSizeOk returns a tuple with the MaxBatchSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SObjectDescribes) GetMaxBatchSizeOk() (*int32, bool) {
	if o == nil || isNil(o.MaxBatchSize) {
		return nil, false
	}
	return o.MaxBatchSize, true
}

// HasMaxBatchSize returns a boolean if a field has been set.
func (o *SObjectDescribes) HasMaxBatchSize() bool {
	if o != nil && !isNil(o.MaxBatchSize) {
		return true
	}

	return false
}

// SetMaxBatchSize gets a reference to the given int32 and assigns it to the MaxBatchSize field.
func (o *SObjectDescribes) SetMaxBatchSize(v int32) {
	o.MaxBatchSize = &v
}

// GetSobjects returns the Sobjects field value if set, zero value otherwise.
func (o *SObjectDescribes) GetSobjects() []SObjectDescribe {
	if o == nil || isNil(o.Sobjects) {
		var ret []SObjectDescribe
		return ret
	}
	return o.Sobjects
}

// GetSobjectsOk returns a tuple with the Sobjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SObjectDescribes) GetSobjectsOk() ([]SObjectDescribe, bool) {
	if o == nil || isNil(o.Sobjects) {
		return nil, false
	}
	return o.Sobjects, true
}

// HasSobjects returns a boolean if a field has been set.
func (o *SObjectDescribes) HasSobjects() bool {
	if o != nil && !isNil(o.Sobjects) {
		return true
	}

	return false
}

// SetSobjects gets a reference to the given []SObjectDescribe and assigns it to the Sobjects field.
func (o *SObjectDescribes) SetSobjects(v []SObjectDescribe) {
	o.Sobjects = v
}

func (o SObjectDescribes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Encoding) {
		toSerialize["encoding"] = o.Encoding
	}
	if !isNil(o.MaxBatchSize) {
		toSerialize["maxBatchSize"] = o.MaxBatchSize
	}
	if !isNil(o.Sobjects) {
		toSerialize["sobjects"] = o.Sobjects
	}
	return json.Marshal(toSerialize)
}

type NullableSObjectDescribes struct {
	value *SObjectDescribes
	isSet bool
}

func (v NullableSObjectDescribes) Get() *SObjectDescribes {
	return v.value
}

func (v *NullableSObjectDescribes) Set(val *SObjectDescribes) {
	v.value = val
	v.isSet = true
}

func (v NullableSObjectDescribes) IsSet() bool {
	return v.isSet
}

func (v *NullableSObjectDescribes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSObjectDescribes(val *SObjectDescribes) *NullableSObjectDescribes {
	return &NullableSObjectDescribes{value: val, isSet: true}
}

func (v NullableSObjectDescribes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSObjectDescribes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
