/*
Salesforce Platform REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 56.0
Contact: russell-laboe@outlook.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rest

import (
	"encoding/json"
)

// SupportedScopes struct for SupportedScopes
type SupportedScopes struct {
	Label *string `json:"label,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// NewSupportedScopes instantiates a new SupportedScopes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupportedScopes() *SupportedScopes {
	this := SupportedScopes{}
	return &this
}

// NewSupportedScopesWithDefaults instantiates a new SupportedScopes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupportedScopesWithDefaults() *SupportedScopes {
	this := SupportedScopes{}
	return &this
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *SupportedScopes) GetLabel() string {
	if o == nil || isNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupportedScopes) GetLabelOk() (*string, bool) {
	if o == nil || isNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *SupportedScopes) HasLabel() bool {
	if o != nil && !isNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *SupportedScopes) SetLabel(v string) {
	o.Label = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SupportedScopes) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupportedScopes) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SupportedScopes) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SupportedScopes) SetName(v string) {
	o.Name = &v
}

func (o SupportedScopes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableSupportedScopes struct {
	value *SupportedScopes
	isSet bool
}

func (v NullableSupportedScopes) Get() *SupportedScopes {
	return v.value
}

func (v *NullableSupportedScopes) Set(val *SupportedScopes) {
	v.value = val
	v.isSet = true
}

func (v NullableSupportedScopes) IsSet() bool {
	return v.isSet
}

func (v *NullableSupportedScopes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupportedScopes(val *SupportedScopes) *NullableSupportedScopes {
	return &NullableSupportedScopes{value: val, isSet: true}
}

func (v NullableSupportedScopes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupportedScopes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
