codegen:
	openapi-generator-cli generate -c codegencfg.json -i pkg/auth/api/openapi.yaml --package-name auth -o pkg/auth
	openapi-generator-cli generate -c codegencfg.json -i pkg/bulkv2/api/openapi.yaml --package-name bulkv2 -o pkg/bulkv2
	openapi-generator-cli generate -c codegencfg.json -i pkg/rest/api/openapi.yaml --package-name rest -o pkg/rest
	go fmt ./...
	go fmt ./...
codegen-auth:
	openapi-generator-cli generate -c codegencfg.json -i pkg/auth/api/openapi.yaml --package-name auth -o pkg/auth
	go fmt ./pkg/auth/...
	go fmt ./pkg/auth/...
codegen-bulk:
	openapi-generator-cli generate -c codegencfg.json -i pkg/bulkv2/api/openapi.yaml --package-name bulkv2 -o pkg/bulkv2
	go fmt ./pkg/bulkv2/...
	go fmt ./pkg/bulkv2/...
codegen-rest:
	openapi-generator-cli generate -c codegencfg.json -i pkg/rest/api/openapi.yaml --package-name rest -o pkg/rest
	go fmt ./pkg/rest/...
	go fmt ./pkg/rest/...
codegen-dry:
	openapi-generator-cli generate -c codegencfg.json --dry-run
init-project:
	git config --local core.hooksPath .githooks/
