/*
Salesforce Platform APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 56.0
Contact: russell-laboe@outlook.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"

)

// BulkQueryJobCreateRequest struct for BulkQueryJobCreateRequest
type BulkQueryJobCreateRequest struct {
	// The type of query.
	Operation string `json:"operation"`
	// The format that is used for the results. Currently the only supported value is CSV.
	ContentType *string `json:"contentType,omitempty"`
	// The column delimiter used for CSV job data. The default value is COMMA.
	ColumnDelimiter *string `json:"columnDelimiter,omitempty"`
	// The line ending used for CSV job data, marking the end of a data row. The default is LF.
	LineEnding *string `json:"lineEnding,omitempty"`
	// The query to be performed.
	Query string `json:"query"`
}

// NewBulkQueryJobCreateRequest instantiates a new BulkQueryJobCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkQueryJobCreateRequest(operation string, query string) *BulkQueryJobCreateRequest {
	this := BulkQueryJobCreateRequest{}
	this.Operation = operation
	this.Query = query
	return &this
}

// NewBulkQueryJobCreateRequestWithDefaults instantiates a new BulkQueryJobCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkQueryJobCreateRequestWithDefaults() *BulkQueryJobCreateRequest {
	this := BulkQueryJobCreateRequest{}
	return &this
}

// GetOperation returns the Operation field value
func (o *BulkQueryJobCreateRequest) GetOperation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operation
}

// GetOperationOk returns a tuple with the Operation field value
// and a boolean to check if the value has been set.
func (o *BulkQueryJobCreateRequest) GetOperationOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Operation, true
}

// SetOperation sets field value
func (o *BulkQueryJobCreateRequest) SetOperation(v string) {
	o.Operation = v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *BulkQueryJobCreateRequest) GetContentType() string {
	if o == nil || isNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkQueryJobCreateRequest) GetContentTypeOk() (*string, bool) {
	if o == nil || isNil(o.ContentType) {
    return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *BulkQueryJobCreateRequest) HasContentType() bool {
	if o != nil && !isNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *BulkQueryJobCreateRequest) SetContentType(v string) {
	o.ContentType = &v
}

// GetColumnDelimiter returns the ColumnDelimiter field value if set, zero value otherwise.
func (o *BulkQueryJobCreateRequest) GetColumnDelimiter() string {
	if o == nil || isNil(o.ColumnDelimiter) {
		var ret string
		return ret
	}
	return *o.ColumnDelimiter
}

// GetColumnDelimiterOk returns a tuple with the ColumnDelimiter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkQueryJobCreateRequest) GetColumnDelimiterOk() (*string, bool) {
	if o == nil || isNil(o.ColumnDelimiter) {
    return nil, false
	}
	return o.ColumnDelimiter, true
}

// HasColumnDelimiter returns a boolean if a field has been set.
func (o *BulkQueryJobCreateRequest) HasColumnDelimiter() bool {
	if o != nil && !isNil(o.ColumnDelimiter) {
		return true
	}

	return false
}

// SetColumnDelimiter gets a reference to the given string and assigns it to the ColumnDelimiter field.
func (o *BulkQueryJobCreateRequest) SetColumnDelimiter(v string) {
	o.ColumnDelimiter = &v
}

// GetLineEnding returns the LineEnding field value if set, zero value otherwise.
func (o *BulkQueryJobCreateRequest) GetLineEnding() string {
	if o == nil || isNil(o.LineEnding) {
		var ret string
		return ret
	}
	return *o.LineEnding
}

// GetLineEndingOk returns a tuple with the LineEnding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkQueryJobCreateRequest) GetLineEndingOk() (*string, bool) {
	if o == nil || isNil(o.LineEnding) {
    return nil, false
	}
	return o.LineEnding, true
}

// HasLineEnding returns a boolean if a field has been set.
func (o *BulkQueryJobCreateRequest) HasLineEnding() bool {
	if o != nil && !isNil(o.LineEnding) {
		return true
	}

	return false
}

// SetLineEnding gets a reference to the given string and assigns it to the LineEnding field.
func (o *BulkQueryJobCreateRequest) SetLineEnding(v string) {
	o.LineEnding = &v
}

// GetQuery returns the Query field value
func (o *BulkQueryJobCreateRequest) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *BulkQueryJobCreateRequest) GetQueryOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *BulkQueryJobCreateRequest) SetQuery(v string) {
	o.Query = v
}

func (o BulkQueryJobCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["operation"] = o.Operation
	}
	if !isNil(o.ContentType) {
		toSerialize["contentType"] = o.ContentType
	}
	if !isNil(o.ColumnDelimiter) {
		toSerialize["columnDelimiter"] = o.ColumnDelimiter
	}
	if !isNil(o.LineEnding) {
		toSerialize["lineEnding"] = o.LineEnding
	}
	if true {
		toSerialize["query"] = o.Query
	}
	return json.Marshal(toSerialize)
}

type NullableBulkQueryJobCreateRequest struct {
	value *BulkQueryJobCreateRequest
	isSet bool
}

func (v NullableBulkQueryJobCreateRequest) Get() *BulkQueryJobCreateRequest {
	return v.value
}

func (v *NullableBulkQueryJobCreateRequest) Set(val *BulkQueryJobCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkQueryJobCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkQueryJobCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkQueryJobCreateRequest(val *BulkQueryJobCreateRequest) *NullableBulkQueryJobCreateRequest {
	return &NullableBulkQueryJobCreateRequest{value: val, isSet: true}
}

func (v NullableBulkQueryJobCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkQueryJobCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


