/*
Salesforce Platform APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 56.0
Contact: russell-laboe@outlook.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goforce

import (
	"encoding/json"
)

// BulkQueryJobCreateRequestExt struct for BulkQueryJobCreateRequestExt
type BulkQueryJobCreateRequestExt struct {
	// The query to be performed.
	Query *string `json:"query,omitempty"`
}

// NewBulkQueryJobCreateRequestExt instantiates a new BulkQueryJobCreateRequestExt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkQueryJobCreateRequestExt() *BulkQueryJobCreateRequestExt {
	this := BulkQueryJobCreateRequestExt{}
	return &this
}

// NewBulkQueryJobCreateRequestExtWithDefaults instantiates a new BulkQueryJobCreateRequestExt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkQueryJobCreateRequestExtWithDefaults() *BulkQueryJobCreateRequestExt {
	this := BulkQueryJobCreateRequestExt{}
	return &this
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *BulkQueryJobCreateRequestExt) GetQuery() string {
	if o == nil || isNil(o.Query) {
		var ret string
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkQueryJobCreateRequestExt) GetQueryOk() (*string, bool) {
	if o == nil || isNil(o.Query) {
    return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *BulkQueryJobCreateRequestExt) HasQuery() bool {
	if o != nil && !isNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given string and assigns it to the Query field.
func (o *BulkQueryJobCreateRequestExt) SetQuery(v string) {
	o.Query = &v
}

func (o BulkQueryJobCreateRequestExt) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	return json.Marshal(toSerialize)
}

type NullableBulkQueryJobCreateRequestExt struct {
	value *BulkQueryJobCreateRequestExt
	isSet bool
}

func (v NullableBulkQueryJobCreateRequestExt) Get() *BulkQueryJobCreateRequestExt {
	return v.value
}

func (v *NullableBulkQueryJobCreateRequestExt) Set(val *BulkQueryJobCreateRequestExt) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkQueryJobCreateRequestExt) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkQueryJobCreateRequestExt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkQueryJobCreateRequestExt(val *BulkQueryJobCreateRequestExt) *NullableBulkQueryJobCreateRequestExt {
	return &NullableBulkQueryJobCreateRequestExt{value: val, isSet: true}
}

func (v NullableBulkQueryJobCreateRequestExt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkQueryJobCreateRequestExt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


