/*
Salesforce Platform REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 56.0
Contact: russell-laboe@outlook.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tooling

import (
	"encoding/json"
)

// ScopeInfo A scope for an object that can be used to filter object records. For example, Account may have a supported ScopeInfo of “mine” (with a UI label of “My accounts”) which filters only Account records for the current user.
type ScopeInfo struct {
	// UI label for this scope.
	Label *string `json:"label,omitempty"`
	// Name of this scope.
	Name *string `json:"name,omitempty"`
}

// NewScopeInfo instantiates a new ScopeInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScopeInfo() *ScopeInfo {
	this := ScopeInfo{}
	return &this
}

// NewScopeInfoWithDefaults instantiates a new ScopeInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScopeInfoWithDefaults() *ScopeInfo {
	this := ScopeInfo{}
	return &this
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *ScopeInfo) GetLabel() string {
	if o == nil || isNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScopeInfo) GetLabelOk() (*string, bool) {
	if o == nil || isNil(o.Label) {
    return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *ScopeInfo) HasLabel() bool {
	if o != nil && !isNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *ScopeInfo) SetLabel(v string) {
	o.Label = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ScopeInfo) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScopeInfo) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ScopeInfo) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ScopeInfo) SetName(v string) {
	o.Name = &v
}

func (o ScopeInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableScopeInfo struct {
	value *ScopeInfo
	isSet bool
}

func (v NullableScopeInfo) Get() *ScopeInfo {
	return v.value
}

func (v *NullableScopeInfo) Set(val *ScopeInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableScopeInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableScopeInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScopeInfo(val *ScopeInfo) *NullableScopeInfo {
	return &NullableScopeInfo{value: val, isSet: true}
}

func (v NullableScopeInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScopeInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


