
example:
  mruEnabled: true
  updateable: true
  activateable: true
  childRelationships:
    - relationshipName: Accounts__r
      field: Primary_Contact__c
      deprecatedAndHidden: true
      junctionReferenceTo:
        - "{}"
        - "{}"
      junctionIdListNames:
        - "{}"
        - "{}"
      childSObject: Account
      cascadeDelete: true
      restrictedDelete: true
    - relationshipName: Accounts__r
      field: Primary_Contact__c
      deprecatedAndHidden: true
      junctionReferenceTo:
        - "{}"
        - "{}"
      junctionIdListNames:
        - "{}"
        - "{}"
      childSObject: Account
      cascadeDelete: true
      restrictedDelete: true
  recordTypeInfos:
    - defaultRecordTypeMapping: true
      urls:
        layout: /services/data/v56.0/sobjects/Contact/describe/layouts/012000000000000AAA
      recordTypeId: 012000000000000AAA
      available: true
      name: Master
      active: true
      developerName: Master
      master: true
    - defaultRecordTypeMapping: true
      urls:
        layout: /services/data/v56.0/sobjects/Contact/describe/layouts/012000000000000AAA
      recordTypeId: 012000000000000AAA
      available: true
      name: Master
      active: true
      developerName: Master
      master: true
  deprecatedAndHidden: true
  supportedScopes:
    - name: everything
      label: All contacts
    - name: everything
      label: All contacts
  searchLayoutable: true
  sobjectDescribeOption: FULL
  deletable: true
  replicateable: true
  actionOverrides:
    - formFactor: LARGE
      name: View
      pageId: 0M03b000000PGADCA4
      url: url
      isAvailableInTouch: true
    - formFactor: LARGE
      name: View
      pageId: 0M03b000000PGADCA4
      url: url
      isAvailableInTouch: true
  isSubtype: true
  lookupLayoutable: lookupLayoutable
  listviewable: listviewable
  mergeable: true
  urls: "{}"
  compactLayoutable: true
  feedEnabled: true
  extendsInterfaces: extendsInterfaces
  networkScopeFieldName: networkScopeFieldName
  customSetting: true
  isInterface: true
  implementedBy: implementedBy
  implementsInterfaces: implementsInterfaces
  extendedBy: extendedBy
  defaultImplementation: defaultImplementation
  deepCloneable: true
  layoutable: true
  custom: true
  associateParentEntity: associateParentEntity
  undeletable: true
  label: Contact
  keyPrefix: "3"
  searchable: true
  namedLayoutInfos:
    - ""
    - ""
  queryable: true
  createable: true
  retrieveable: true
  associateEntityType: associateEntityType
  hasSubtypes: true
  name: Contact
  fields:
    - defaultValue: defaultValue
      precision: 0
      compoundFieldName: compoundFieldName
      nameField: true
      type: id
      restrictedDelete: true
      relationshipName: relationshipName
      calculatedFormula: calculatedFormula
      controllerName: controllerName
      namePointing: true
      defaultValueFormula: defaultValueFormula
      calculated: true
      writeRequiresMasterRead: true
      inlineHelpText: inlineHelpText
      picklistValues:
        - validFor: validFor
          defaultValue: true
          active: true
          label: Bishop
          value: Bishop
        - validFor: validFor
          defaultValue: true
          active: true
          label: Bishop
          value: Bishop
      aiPredictionField: true
      filterable: true
      maskType: maskType
      queryByDistance: true
      caseSensitive: true
      aggregatable: true
      referenceTo:
        - User
        - User
      soapType: tns:ID
      unique: true
      name: Id
      highScaleNumber: true
      idLookup: true
      displayLocationInDecimal: true
      defaultedOnCreate: true
      updateable: true
      deprecatedAndHidden: true
      byteLength: 18
      scale: 0
      polymorphicForeignKey: true
      nillable: true
      htmlFormatted: true
      referenceTargetField: referenceTargetField
      cascadeDelete: true
      mask: mask
      permissionable: true
      relationshipOrder: relationshipOrder
      custom: true
      length: 18
      externalId: true
      dependentPicklist: true
      label: Contact ID
      sortable: true
      autoNumber: true
      filteredLookupInfo: filteredLookupInfo
      restrictedPicklist: true
      createable: true
      encrypted: true
      searchPrefilterable: true
      extraTypeInfo: extraTypeInfo
      groupable: true
      digits: 0
      formulaTreatNullNumberAsZero: true
    - defaultValue: defaultValue
      precision: 0
      compoundFieldName: compoundFieldName
      nameField: true
      type: id
      restrictedDelete: true
      relationshipName: relationshipName
      calculatedFormula: calculatedFormula
      controllerName: controllerName
      namePointing: true
      defaultValueFormula: defaultValueFormula
      calculated: true
      writeRequiresMasterRead: true
      inlineHelpText: inlineHelpText
      picklistValues:
        - validFor: validFor
          defaultValue: true
          active: true
          label: Bishop
          value: Bishop
        - validFor: validFor
          defaultValue: true
          active: true
          label: Bishop
          value: Bishop
      aiPredictionField: true
      filterable: true
      maskType: maskType
      queryByDistance: true
      caseSensitive: true
      aggregatable: true
      referenceTo:
        - User
        - User
      soapType: tns:ID
      unique: true
      name: Id
      highScaleNumber: true
      idLookup: true
      displayLocationInDecimal: true
      defaultedOnCreate: true
      updateable: true
      deprecatedAndHidden: true
      byteLength: 18
      scale: 0
      polymorphicForeignKey: true
      nillable: true
      htmlFormatted: true
      referenceTargetField: referenceTargetField
      cascadeDelete: true
      mask: mask
      permissionable: true
      relationshipOrder: relationshipOrder
      custom: true
      length: 18
      externalId: true
      dependentPicklist: true
      label: Contact ID
      sortable: true
      autoNumber: true
      filteredLookupInfo: filteredLookupInfo
      restrictedPicklist: true
      createable: true
      encrypted: true
      searchPrefilterable: true
      extraTypeInfo: extraTypeInfo
      groupable: true
      digits: 0
      formulaTreatNullNumberAsZero: true
  labelPlural: Contacts
  triggerable: true
properties:
  activateable:
    type: boolean
  associateEntityType:
    nullable: true
    type: string
  associateParentEntity:
    nullable: true
    type: string
  compactLayoutable:
    type: boolean
  createable:
    type: boolean
  custom:
    type: boolean
  customSetting:
    type: boolean
  deepCloneable:
    type: boolean
  defaultImplementation:
    nullable: true
    type: string
  deletable:
    type: boolean
  deprecatedAndHidden:
    type: boolean
  extendedBy:
    nullable: true
    type: string
  extendsInterfaces:
    nullable: true
    type: string
  feedEnabled:
    type: boolean
  hasSubtypes:
    type: boolean
  implementedBy:
    nullable: true
    type: string
  implementsInterfaces:
    nullable: true
    type: string
  isInterface:
    type: boolean
  isSubtype:
    type: boolean
  keyPrefix:
    example: "3"
    type: string
  label:
    example: Contact
    type: string
  labelPlural:
    example: Contacts
    type: string
  layoutable:
    type: boolean
  listviewable:
    nullable: true
    type: string
  lookupLayoutable:
    nullable: true
    type: string
  mergeable:
    type: boolean
  mruEnabled:
    type: boolean
  name:
    example: Contact
    type: string
  networkScopeFieldName:
    nullable: true
    type: string
  queryable:
    type: boolean
  replicateable:
    type: boolean
  retrieveable:
    type: boolean
  searchLayoutable:
    type: boolean
  searchable:
    type: boolean
  sobjectDescribeOption:
    example: FULL
    type: string
  triggerable:
    type: boolean
  undeletable:
    type: boolean
  updateable:
    type: boolean
  namedLayoutInfos:
    items: {}
    type: array
  actionOverrides:
    items:
      $ref: '#/components/schemas/sObjectDescribeActionOverrides'
    type: array
  childRelationships:
    items:
      $ref: '#/components/schemas/sObjectDescribeChildRelationships'
    type: array
  recordTypeInfos:
    items:
      $ref: '#/components/schemas/sObjectRecordTypeInfo'
    type: array
  supportedScopes:
    items:
      $ref: '#/components/schemas/sObjectDescribeSupportedScopes'
    type: array
  urls:
    type: object
  fields:
    items:
      $ref: '#/components/schemas/sObjectFieldDescribe'
    type: array
required:
  - keyPrefix
  - label
  - labelPlural
  - name
title: sObjectDescribe
type: object