/*
Salesforce Platform Bulk V2 APIs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 56.0
Contact: russell-laboe@outlook.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bulkv2

import (
	"encoding/json"
)

// QueryJobInfo struct for QueryJobInfo
type QueryJobInfo struct {
	// The unique ID for this job.
	Id string `json:"id"`
	// The object type being queried.
	Object string `json:"object"`
	// The ID of the user who created the job.
	CreatedById string `json:"createdById"`
	// The UTC date and time when the job was created.
	CreatedDate string `json:"createdDate"`
	// The UTC date and time when the API last updated the job information.
	SystemModstamp string `json:"systemModstamp"`
	// The current state of processing for the job.
	State string `json:"state"`
	// Reserved for future use. How the request is processed. Currently only parallel mode is supported. (When other modes are added, the API chooses the mode automatically. The mode isn’t user configurable.)
	ConcurrencyMode string `json:"concurrencyMode"`
	// The API version that the job was created in.
	ApiVersion float32 `json:"apiVersion"`
	// The job’s type. For a query job, the type is always V2Query.
	JobType *string `json:"jobType,omitempty"`
	// The number of records processed in this job.
	NumberRecordsProcessed *int64 `json:"numberRecordsProcessed,omitempty"`
	// The number of times that Salesforce attempted to save the results of an operation. Repeated attempts indicate a problem such as a lock contention.
	Retries *int32 `json:"retries,omitempty"`
	// The number of milliseconds taken to process the job.
	TotalProcessingTime *int64 `json:"totalProcessingTime,omitempty"`
	// The type of query.
	Operation string `json:"operation"`
	// The format that is used for the results. Currently the only supported value is CSV.
	ContentType string `json:"contentType"`
	// The column delimiter used for CSV job data. The default value is COMMA.
	ColumnDelimiter *string `json:"columnDelimiter,omitempty"`
	// The line ending used for CSV job data, marking the end of a data row. The default is LF.
	LineEnding *string `json:"lineEnding,omitempty"`
}

// NewQueryJobInfo instantiates a new QueryJobInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryJobInfo(id string, object string, createdById string, createdDate string, systemModstamp string, state string, concurrencyMode string, apiVersion float32, operation string, contentType string) *QueryJobInfo {
	this := QueryJobInfo{}
	this.Id = id
	this.Object = object
	this.CreatedById = createdById
	this.CreatedDate = createdDate
	this.SystemModstamp = systemModstamp
	this.State = state
	this.ConcurrencyMode = concurrencyMode
	this.ApiVersion = apiVersion
	this.Operation = operation
	this.ContentType = contentType
	return &this
}

// NewQueryJobInfoWithDefaults instantiates a new QueryJobInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryJobInfoWithDefaults() *QueryJobInfo {
	this := QueryJobInfo{}
	return &this
}

// GetId returns the Id field value
func (o *QueryJobInfo) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *QueryJobInfo) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *QueryJobInfo) SetId(v string) {
	o.Id = v
}

// GetObject returns the Object field value
func (o *QueryJobInfo) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *QueryJobInfo) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *QueryJobInfo) SetObject(v string) {
	o.Object = v
}

// GetCreatedById returns the CreatedById field value
func (o *QueryJobInfo) GetCreatedById() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedById
}

// GetCreatedByIdOk returns a tuple with the CreatedById field value
// and a boolean to check if the value has been set.
func (o *QueryJobInfo) GetCreatedByIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedById, true
}

// SetCreatedById sets field value
func (o *QueryJobInfo) SetCreatedById(v string) {
	o.CreatedById = v
}

// GetCreatedDate returns the CreatedDate field value
func (o *QueryJobInfo) GetCreatedDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value
// and a boolean to check if the value has been set.
func (o *QueryJobInfo) GetCreatedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedDate, true
}

// SetCreatedDate sets field value
func (o *QueryJobInfo) SetCreatedDate(v string) {
	o.CreatedDate = v
}

// GetSystemModstamp returns the SystemModstamp field value
func (o *QueryJobInfo) GetSystemModstamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SystemModstamp
}

// GetSystemModstampOk returns a tuple with the SystemModstamp field value
// and a boolean to check if the value has been set.
func (o *QueryJobInfo) GetSystemModstampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SystemModstamp, true
}

// SetSystemModstamp sets field value
func (o *QueryJobInfo) SetSystemModstamp(v string) {
	o.SystemModstamp = v
}

// GetState returns the State field value
func (o *QueryJobInfo) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *QueryJobInfo) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *QueryJobInfo) SetState(v string) {
	o.State = v
}

// GetConcurrencyMode returns the ConcurrencyMode field value
func (o *QueryJobInfo) GetConcurrencyMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConcurrencyMode
}

// GetConcurrencyModeOk returns a tuple with the ConcurrencyMode field value
// and a boolean to check if the value has been set.
func (o *QueryJobInfo) GetConcurrencyModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConcurrencyMode, true
}

// SetConcurrencyMode sets field value
func (o *QueryJobInfo) SetConcurrencyMode(v string) {
	o.ConcurrencyMode = v
}

// GetApiVersion returns the ApiVersion field value
func (o *QueryJobInfo) GetApiVersion() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value
// and a boolean to check if the value has been set.
func (o *QueryJobInfo) GetApiVersionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiVersion, true
}

// SetApiVersion sets field value
func (o *QueryJobInfo) SetApiVersion(v float32) {
	o.ApiVersion = v
}

// GetJobType returns the JobType field value if set, zero value otherwise.
func (o *QueryJobInfo) GetJobType() string {
	if o == nil || isNil(o.JobType) {
		var ret string
		return ret
	}
	return *o.JobType
}

// GetJobTypeOk returns a tuple with the JobType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryJobInfo) GetJobTypeOk() (*string, bool) {
	if o == nil || isNil(o.JobType) {
		return nil, false
	}
	return o.JobType, true
}

// HasJobType returns a boolean if a field has been set.
func (o *QueryJobInfo) HasJobType() bool {
	if o != nil && !isNil(o.JobType) {
		return true
	}

	return false
}

// SetJobType gets a reference to the given string and assigns it to the JobType field.
func (o *QueryJobInfo) SetJobType(v string) {
	o.JobType = &v
}

// GetNumberRecordsProcessed returns the NumberRecordsProcessed field value if set, zero value otherwise.
func (o *QueryJobInfo) GetNumberRecordsProcessed() int64 {
	if o == nil || isNil(o.NumberRecordsProcessed) {
		var ret int64
		return ret
	}
	return *o.NumberRecordsProcessed
}

// GetNumberRecordsProcessedOk returns a tuple with the NumberRecordsProcessed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryJobInfo) GetNumberRecordsProcessedOk() (*int64, bool) {
	if o == nil || isNil(o.NumberRecordsProcessed) {
		return nil, false
	}
	return o.NumberRecordsProcessed, true
}

// HasNumberRecordsProcessed returns a boolean if a field has been set.
func (o *QueryJobInfo) HasNumberRecordsProcessed() bool {
	if o != nil && !isNil(o.NumberRecordsProcessed) {
		return true
	}

	return false
}

// SetNumberRecordsProcessed gets a reference to the given int64 and assigns it to the NumberRecordsProcessed field.
func (o *QueryJobInfo) SetNumberRecordsProcessed(v int64) {
	o.NumberRecordsProcessed = &v
}

// GetRetries returns the Retries field value if set, zero value otherwise.
func (o *QueryJobInfo) GetRetries() int32 {
	if o == nil || isNil(o.Retries) {
		var ret int32
		return ret
	}
	return *o.Retries
}

// GetRetriesOk returns a tuple with the Retries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryJobInfo) GetRetriesOk() (*int32, bool) {
	if o == nil || isNil(o.Retries) {
		return nil, false
	}
	return o.Retries, true
}

// HasRetries returns a boolean if a field has been set.
func (o *QueryJobInfo) HasRetries() bool {
	if o != nil && !isNil(o.Retries) {
		return true
	}

	return false
}

// SetRetries gets a reference to the given int32 and assigns it to the Retries field.
func (o *QueryJobInfo) SetRetries(v int32) {
	o.Retries = &v
}

// GetTotalProcessingTime returns the TotalProcessingTime field value if set, zero value otherwise.
func (o *QueryJobInfo) GetTotalProcessingTime() int64 {
	if o == nil || isNil(o.TotalProcessingTime) {
		var ret int64
		return ret
	}
	return *o.TotalProcessingTime
}

// GetTotalProcessingTimeOk returns a tuple with the TotalProcessingTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryJobInfo) GetTotalProcessingTimeOk() (*int64, bool) {
	if o == nil || isNil(o.TotalProcessingTime) {
		return nil, false
	}
	return o.TotalProcessingTime, true
}

// HasTotalProcessingTime returns a boolean if a field has been set.
func (o *QueryJobInfo) HasTotalProcessingTime() bool {
	if o != nil && !isNil(o.TotalProcessingTime) {
		return true
	}

	return false
}

// SetTotalProcessingTime gets a reference to the given int64 and assigns it to the TotalProcessingTime field.
func (o *QueryJobInfo) SetTotalProcessingTime(v int64) {
	o.TotalProcessingTime = &v
}

// GetOperation returns the Operation field value
func (o *QueryJobInfo) GetOperation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operation
}

// GetOperationOk returns a tuple with the Operation field value
// and a boolean to check if the value has been set.
func (o *QueryJobInfo) GetOperationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operation, true
}

// SetOperation sets field value
func (o *QueryJobInfo) SetOperation(v string) {
	o.Operation = v
}

// GetContentType returns the ContentType field value
func (o *QueryJobInfo) GetContentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *QueryJobInfo) GetContentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *QueryJobInfo) SetContentType(v string) {
	o.ContentType = v
}

// GetColumnDelimiter returns the ColumnDelimiter field value if set, zero value otherwise.
func (o *QueryJobInfo) GetColumnDelimiter() string {
	if o == nil || isNil(o.ColumnDelimiter) {
		var ret string
		return ret
	}
	return *o.ColumnDelimiter
}

// GetColumnDelimiterOk returns a tuple with the ColumnDelimiter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryJobInfo) GetColumnDelimiterOk() (*string, bool) {
	if o == nil || isNil(o.ColumnDelimiter) {
		return nil, false
	}
	return o.ColumnDelimiter, true
}

// HasColumnDelimiter returns a boolean if a field has been set.
func (o *QueryJobInfo) HasColumnDelimiter() bool {
	if o != nil && !isNil(o.ColumnDelimiter) {
		return true
	}

	return false
}

// SetColumnDelimiter gets a reference to the given string and assigns it to the ColumnDelimiter field.
func (o *QueryJobInfo) SetColumnDelimiter(v string) {
	o.ColumnDelimiter = &v
}

// GetLineEnding returns the LineEnding field value if set, zero value otherwise.
func (o *QueryJobInfo) GetLineEnding() string {
	if o == nil || isNil(o.LineEnding) {
		var ret string
		return ret
	}
	return *o.LineEnding
}

// GetLineEndingOk returns a tuple with the LineEnding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryJobInfo) GetLineEndingOk() (*string, bool) {
	if o == nil || isNil(o.LineEnding) {
		return nil, false
	}
	return o.LineEnding, true
}

// HasLineEnding returns a boolean if a field has been set.
func (o *QueryJobInfo) HasLineEnding() bool {
	if o != nil && !isNil(o.LineEnding) {
		return true
	}

	return false
}

// SetLineEnding gets a reference to the given string and assigns it to the LineEnding field.
func (o *QueryJobInfo) SetLineEnding(v string) {
	o.LineEnding = &v
}

func (o QueryJobInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["object"] = o.Object
	}
	if true {
		toSerialize["createdById"] = o.CreatedById
	}
	if true {
		toSerialize["createdDate"] = o.CreatedDate
	}
	if true {
		toSerialize["systemModstamp"] = o.SystemModstamp
	}
	if true {
		toSerialize["state"] = o.State
	}
	if true {
		toSerialize["concurrencyMode"] = o.ConcurrencyMode
	}
	if true {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	if !isNil(o.JobType) {
		toSerialize["jobType"] = o.JobType
	}
	if !isNil(o.NumberRecordsProcessed) {
		toSerialize["numberRecordsProcessed"] = o.NumberRecordsProcessed
	}
	if !isNil(o.Retries) {
		toSerialize["retries"] = o.Retries
	}
	if !isNil(o.TotalProcessingTime) {
		toSerialize["totalProcessingTime"] = o.TotalProcessingTime
	}
	if true {
		toSerialize["operation"] = o.Operation
	}
	if true {
		toSerialize["contentType"] = o.ContentType
	}
	if !isNil(o.ColumnDelimiter) {
		toSerialize["columnDelimiter"] = o.ColumnDelimiter
	}
	if !isNil(o.LineEnding) {
		toSerialize["lineEnding"] = o.LineEnding
	}
	return json.Marshal(toSerialize)
}

type NullableQueryJobInfo struct {
	value *QueryJobInfo
	isSet bool
}

func (v NullableQueryJobInfo) Get() *QueryJobInfo {
	return v.value
}

func (v *NullableQueryJobInfo) Set(val *QueryJobInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryJobInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryJobInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryJobInfo(val *QueryJobInfo) *NullableQueryJobInfo {
	return &NullableQueryJobInfo{value: val, isSet: true}
}

func (v NullableQueryJobInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryJobInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
