/*
Salesforce Platform Bulk V2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 56.0
Contact: russell-laboe@outlook.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bulkv2

import (
	"encoding/json"
	"fmt"
)

// CreateQueryJobRequest struct for CreateQueryJobRequest

type CreateQueryJobRequestOperation int

const (
	CREATE_QUERY_JOB_REQUEST_OPERATION_QUERY CreateQueryJobRequestOperation = iota
	CREATE_QUERY_JOB_REQUEST_OPERATION_QUERY_ALL
)

func (e *CreateQueryJobRequestOperation) String() string {
	s := []string{"query", "queryAll"}[*e]
	return s
}
func (e CreateQueryJobRequestOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e *CreateQueryJobRequestOperation) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return err
	}
	e, err := CreateQueryJobRequestOperationParse(str)

	return err
}
func CreateQueryJobRequestOperationParse(s string) (*CreateQueryJobRequestOperation, error) {
	for i, e := range []string{"query", "queryAll"} {
		if s == e {
			enum := CreateQueryJobRequestOperation(i)
			return &enum, nil
		}
	}
	return nil, fmt.Errorf("%q is not a valid CreateQueryJobRequestOperation", s)
}

type CreateQueryJobRequestContentType int

const (
	CREATE_QUERY_JOB_REQUEST_CONTENT_TYPE_CSV CreateQueryJobRequestContentType = iota
)

func (e *CreateQueryJobRequestContentType) String() string {
	s := []string{"CSV"}[*e]
	return s
}
func (e CreateQueryJobRequestContentType) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e *CreateQueryJobRequestContentType) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return err
	}
	e, err := CreateQueryJobRequestContentTypeParse(str)

	return err
}
func CreateQueryJobRequestContentTypeParse(s string) (*CreateQueryJobRequestContentType, error) {
	for i, e := range []string{"CSV"} {
		if s == e {
			enum := CreateQueryJobRequestContentType(i)
			return &enum, nil
		}
	}
	return nil, fmt.Errorf("%q is not a valid CreateQueryJobRequestContentType", s)
}

type CreateQueryJobRequestColumnDelimiter int

const (
	CREATE_QUERY_JOB_REQUEST_COLUMN_DELIMITER_BACKQUOTE CreateQueryJobRequestColumnDelimiter = iota
	CREATE_QUERY_JOB_REQUEST_COLUMN_DELIMITER_CARET
	CREATE_QUERY_JOB_REQUEST_COLUMN_DELIMITER_COMMA
	CREATE_QUERY_JOB_REQUEST_COLUMN_DELIMITER_PIPE
	CREATE_QUERY_JOB_REQUEST_COLUMN_DELIMITER_SEMICOLON
	CREATE_QUERY_JOB_REQUEST_COLUMN_DELIMITER_TAB
)

func (e *CreateQueryJobRequestColumnDelimiter) String() *string {
	s := []string{"BACKQUOTE", "CARET", "COMMA", "PIPE", "SEMICOLON", "TAB"}[*e]
	return &s
}
func (e *CreateQueryJobRequestColumnDelimiter) Get() *string {
	return e.String()
}
func (e *CreateQueryJobRequestColumnDelimiter) IsSet() bool {
	return e != nil
}
func (e *CreateQueryJobRequestColumnDelimiter) Set(val *CreateQueryJobRequestColumnDelimiter) {
	e = val
}
func (e *CreateQueryJobRequestColumnDelimiter) Unset() {
	e.Set(nil)
}
func (e CreateQueryJobRequestColumnDelimiter) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e *CreateQueryJobRequestColumnDelimiter) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return err
	}
	e, err := CreateQueryJobRequestColumnDelimiterParse(str)

	return err
}
func CreateQueryJobRequestColumnDelimiterParse(s string) (*CreateQueryJobRequestColumnDelimiter, error) {
	for i, e := range []string{"BACKQUOTE", "CARET", "COMMA", "PIPE", "SEMICOLON", "TAB"} {
		if s == e {
			enum := CreateQueryJobRequestColumnDelimiter(i)
			return &enum, nil
		}
	}
	return nil, fmt.Errorf("%q is not a valid CreateQueryJobRequestColumnDelimiter", s)
}

type CreateQueryJobRequestLineEnding int

const (
	CREATE_QUERY_JOB_REQUEST_LINE_ENDING_LF CreateQueryJobRequestLineEnding = iota
	CREATE_QUERY_JOB_REQUEST_LINE_ENDING_CRLF
)

func (e *CreateQueryJobRequestLineEnding) String() string {
	s := []string{"LF", "CRLF"}[*e]
	return s
}
func (e CreateQueryJobRequestLineEnding) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e *CreateQueryJobRequestLineEnding) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return err
	}
	e, err := CreateQueryJobRequestLineEndingParse(str)

	return err
}
func CreateQueryJobRequestLineEndingParse(s string) (*CreateQueryJobRequestLineEnding, error) {
	for i, e := range []string{"LF", "CRLF"} {
		if s == e {
			enum := CreateQueryJobRequestLineEnding(i)
			return &enum, nil
		}
	}
	return nil, fmt.Errorf("%q is not a valid CreateQueryJobRequestLineEnding", s)
}

type CreateQueryJobRequest struct {
	// The type of query.
	Operation CreateQueryJobRequestOperation `json:"operation"`
	// The format that is used for the results. Currently the only supported value is CSV.
	ContentType *CreateQueryJobRequestContentType `json:"contentType,omitempty"`
	// The column delimiter used for CSV job data. The default value is COMMA.
	ColumnDelimiter CreateQueryJobRequestColumnDelimiter `json:"columnDelimiter,omitempty"`
	// The line ending used for CSV job data, marking the end of a data row. The default is LF.
	LineEnding *CreateQueryJobRequestLineEnding `json:"lineEnding,omitempty"`
	// The query to be performed.
	Query string `json:"query"`
}

// NewCreateQueryJobRequest instantiates a new CreateQueryJobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateQueryJobRequest(operation CreateQueryJobRequestOperation, query string) *CreateQueryJobRequest {
	this := CreateQueryJobRequest{}
	this.Operation = operation
	this.Query = query
	return &this
}

// NewCreateQueryJobRequestWithDefaults instantiates a new CreateQueryJobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateQueryJobRequestWithDefaults() *CreateQueryJobRequest {
	this := CreateQueryJobRequest{}
	return &this
}

// GetOperation returns the Operation field value
func (o *CreateQueryJobRequest) GetOperation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operation.String()
}

// GetOperationOk returns a tuple with the Operation field value
// and a boolean to check if the value has been set.
func (o *CreateQueryJobRequest) GetOperationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	s := o.Operation.String()
	return &s, true
}

// SetOperation sets field value
func (o *CreateQueryJobRequest) SetOperation(v CreateQueryJobRequestOperation) {
	o.Operation = v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *CreateQueryJobRequest) GetContentType() string {
	if o == nil || isNil(o.ContentType) {
		var ret string
		return ret
	}
	return o.ContentType.String()
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateQueryJobRequest) GetContentTypeOk() (*string, bool) {
	if o == nil || isNil(o.ContentType) {
		return nil, false
	}
	s := o.ContentType.String()
	return &s, true
}

// HasContentType returns a boolean if a field has been set.
func (o *CreateQueryJobRequest) HasContentType() bool {
	if o != nil && !isNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *CreateQueryJobRequest) SetContentType(v CreateQueryJobRequestContentType) {
	o.ContentType = &v
}

// GetColumnDelimiter returns the ColumnDelimiter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateQueryJobRequest) GetColumnDelimiter() string {
	if o == nil || isNil(o.ColumnDelimiter.Get()) {
		var ret string
		return ret
	}
	return *o.ColumnDelimiter.Get()
}

// GetColumnDelimiterOk returns a tuple with the ColumnDelimiter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateQueryJobRequest) GetColumnDelimiterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ColumnDelimiter.Get(), o.ColumnDelimiter.IsSet()
}

// HasColumnDelimiter returns a boolean if a field has been set.
func (o *CreateQueryJobRequest) HasColumnDelimiter() bool {
	if o != nil && o.ColumnDelimiter.IsSet() {
		return true
	}

	return false
}

// SetColumnDelimiter gets a reference to the given NullableString and assigns it to the ColumnDelimiter field.
func (o *CreateQueryJobRequest) SetColumnDelimiter(v CreateQueryJobRequestColumnDelimiter) {
	o.ColumnDelimiter.Set(&v)
}

// SetColumnDelimiterNil sets the value for ColumnDelimiter to be an explicit nil
func (o *CreateQueryJobRequest) SetColumnDelimiterNil() {
	o.ColumnDelimiter.Set(nil)
}

// UnsetColumnDelimiter ensures that no value is present for ColumnDelimiter, not even an explicit nil
func (o *CreateQueryJobRequest) UnsetColumnDelimiter() {
	o.ColumnDelimiter.Unset()
}

// GetLineEnding returns the LineEnding field value if set, zero value otherwise.
func (o *CreateQueryJobRequest) GetLineEnding() string {
	if o == nil || isNil(o.LineEnding) {
		var ret string
		return ret
	}
	return o.LineEnding.String()
}

// GetLineEndingOk returns a tuple with the LineEnding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateQueryJobRequest) GetLineEndingOk() (*string, bool) {
	if o == nil || isNil(o.LineEnding) {
		return nil, false
	}
	s := o.LineEnding.String()
	return &s, true
}

// HasLineEnding returns a boolean if a field has been set.
func (o *CreateQueryJobRequest) HasLineEnding() bool {
	if o != nil && !isNil(o.LineEnding) {
		return true
	}

	return false
}

// SetLineEnding gets a reference to the given string and assigns it to the LineEnding field.
func (o *CreateQueryJobRequest) SetLineEnding(v CreateQueryJobRequestLineEnding) {
	o.LineEnding = &v
}

// GetQuery returns the Query field value
func (o *CreateQueryJobRequest) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *CreateQueryJobRequest) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *CreateQueryJobRequest) SetQuery(v string) {
	o.Query = v
}

func (o CreateQueryJobRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["operation"] = o.Operation
	}
	if !isNil(o.ContentType) {
		toSerialize["contentType"] = o.ContentType
	}
	if o.ColumnDelimiter.IsSet() {
		toSerialize["columnDelimiter"] = o.ColumnDelimiter.Get()
	}
	if !isNil(o.LineEnding) {
		toSerialize["lineEnding"] = o.LineEnding
	}
	if true {
		toSerialize["query"] = o.Query
	}
	return json.Marshal(toSerialize)
}

type NullableCreateQueryJobRequest struct {
	value *CreateQueryJobRequest
	isSet bool
}

func (v NullableCreateQueryJobRequest) Get() *CreateQueryJobRequest {
	return v.value
}

func (v *NullableCreateQueryJobRequest) Set(val *CreateQueryJobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateQueryJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateQueryJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateQueryJobRequest(val *CreateQueryJobRequest) *NullableCreateQueryJobRequest {
	return &NullableCreateQueryJobRequest{value: val, isSet: true}
}

func (v NullableCreateQueryJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateQueryJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
